# rule identifiers to exclude from running
disabled_rules:
  - missing_docs

# some rules are only opt-in
opt_in_rules:
  - empty_count
  - force_unwrapping

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Carthage
  - Pods
  - parts

line_length:
  error: 150

identifier_name:
  excluded:
    - id